language: python
sudo: false
python:
  - "2.6"
  - "2.7"
addons:
  apt:
    packages:
      - git-core
install:
  - pip install pyyaml
  - pip install urllib3
  - pip install configobj
  - pip install dirq
before_script:
  - git config --global user.email "noreply@cern.ch"
  - git config --global user.name "Travis CI"
script: nosetests -w src jens.test.update:UpdateTest jens.test.metadata:MetadataTest jens.test.messaging:MessagingTest
